"use client";

import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { StatusProvider } from "@/context/StatusContext";
import { CompanyProvider } from "@/context/CompanyContext";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { AuthProvider } from "@/context/AuthContext";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

// Initialize fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const router = useRouter();

  useEffect(() => {
    // Select body element
    const body = document.body;

    // Set background based on route
    if (router.pathname === '/login') {
      body.style.backgroundColor = '#ffffff'; // white
    } else {
      body.style.backgroundColor = '#e9e9e9'; // default
    }
  }, [router.pathname]);

  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/manifest.json" />

        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Your App Name" />

        <meta name="theme-color" content="#8A2BE2" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />

        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable}`}>
        <div className="fixed top-0 left-0 w-full h-[env(safe-area-inset-top)] bg-[#8A2BE2] z-50"></div>

        <AuthProvider>
          <div className="min-h-screen flex flex-col p-4 font-sans">
            <Header />
            <div className="mt-18">
              <CompanyProvider>
                <StatusProvider>{children}</StatusProvider>
              </CompanyProvider>
            </div>
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
